version: '3'
services:
  nextjs: 
    build: 
      context: ./app
    container_name: "nextjs"
    volumes:
      - .:/var/app/current
    ports: 
      - 3000:3000
    networks: 
      - nextjs-app
  nginx: 
    build: 
      context: ./nginx
    ports: 
      - 80:80
    networks: 
      - nextjs-app
  api: 
    build: ./server
    container_name: "api"
    ports: 
      - 9100:9100
    volumes: 
      - ./server:/api
    networks: 
      - nextjs-app


networks: 
  nextjs-app: {}